[package]
name = "snakebot_rust"
version = "0.1.0"
authors = ["Martin Barksten <martin.barksten@gmail.com>"]

[dependencies]
ws = "0.5.2"
serde = "0.8"
serde_json = "0.8"
serde_macros = "0.8"
quick-error = "1.1.0"
log = "0.3.6"
log4rs = { version = "0.4.6", features = ["toml"] }
