[package]
name = "snakebot_rust"
version = "1.0.0"
authors = ["Martin Barksten <martin.barksten@gmail.com>"]

[dependencies]
ws = "0.5.2"
serde = "= 0.8.8"
serde_json = "= 0.8.0"
serde_macros = "= 0.8.2"
quick-error = "1.1.0"
log = "0.3.6"
log4rs = { version = "0.4.6", features = ["toml"] }
target_info = "0.1.0"
rustc_version = "0.1.0"
