[package]
name = "snakebot_rust"
version = "0.1.0"
authors = ["Martin Barksten <martin.barksten@gmail.com>"]

[dependencies]
ws = "0.4.8"
serde = "0.7.7"
serde_json = "0.7.1"
serde_macros = "0.7.7"
quick-error = "1.1.0"
log = "0.3.6"
log4rs = { version = "0.4.6", features = ["toml"] }
